version: '3.8'
services:
  todo-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_SERVER=your-server.database.windows.net
      - DB_USER=seu-usuario
      - DB_PASSWORD=sua-senha-forte
      - DB_NAME=ToDoDB
      - PORT=3000
    # ⚠️ Não use .env aqui se já estiver passando environment